const $=s=>document.querySelector(s);
const state={files:{'index.html':`<!doctype html><html><head><meta charset="utf-8"><title>GutHeb Space</title><style>body{font-family:system-ui;background:#080b12;color:white;display:grid;place-items:center;min-height:100vh}main{max-width:680px;padding:48px}button{padding:12px 18px;border:0;border-radius:10px}</style></head><body><main><h1>Hello from GutHeb Workers.</h1><p>Edit this file, compile it, then deploy a Pages build.</p><button onclick="document.body.style.background='#17233e'">Try it</button></main></body></html>`,'README.md':'# New GutHeb Space\\n\\nA project created in GutHeb Workers.\\n'},active:'index.html',history:[],projectId:'',runtime:'Web Native',language:'HTML'};
function renderTree(){const el=$('#fileTree');el.innerHTML=Object.keys(state.files).map(f=>`<div class="file ${f===state.active?'active':''}" data-file="${escapeHtml(f)}"><span class="dot"></span>${escapeHtml(f)}</div>`).join('');el.querySelectorAll('.file').forEach(n=>n.onclick=()=>openFile(n.dataset.file));}
function renderTabs(){$('#tabs').innerHTML=Object.keys(state.files).map(f=>`<div class="tab ${f===state.active?'active':''}" data-file="${escapeHtml(f)}">◉<span>${escapeHtml(f)}</span></div>`).join('');$('#tabs').querySelectorAll('.tab').forEach(n=>n.onclick=()=>openFile(n.dataset.file));}
function openFile(name){saveEditor();state.active=name;$('#editor').value=state.files[name];$('#entryLabel').textContent=name;renderTree();renderTabs();updateCursor();}
function saveEditor(){if(state.active)state.files[state.active]=$('#editor').value}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateCursor(){const e=$('#editor'),before=e.value.slice(0,e.selectionStart),lines=before.split('\n');$('#cursor').textContent=`Ln ${lines.length}, Col ${lines.at(-1).length+1}`}
function nativePreview(){saveEditor();const html=state.files['index.html']||'<h1>No index.html</h1>';const frame=$('#preview');frame.srcdoc=html;$('#previewDrawer').classList.add('open');$('#status').textContent='Compiled in browser';$('#buildState').textContent='● Preview ready'}
function build(){const p=$('#progress');p.style.width='15%';$('#status').textContent='Resolving project…';setTimeout(()=>{p.style.width='55%';$('#status').textContent='Compiling target…'},220);setTimeout(()=>{p.style.width='100%';if(state.runtime==='Web Native'||state.language==='HTML'||state.language==='JavaScript'||state.language==='TypeScript'){nativePreview()}else{$('#status').textContent=`${state.language} pipeline prepared`;$('#buildState').textContent='● Backend compiler required';}setTimeout(()=>p.style.width='0',450)},650)}
function aiReply(q){const l=q.toLowerCase();if(l.includes('deploy'))return 'I would package the current workspace, create a deployment ID, upload immutable assets and publish /pages/#id. The UI is ready for that Workers endpoint.';if(l.includes('react')||l.includes('vite')||l.includes('vue'))return 'Framework mode is configured. The next build step is a real package install + framework compiler on the Workers build service, then the generated dist/ becomes the Pages artifact.';return 'I can turn that request into workspace changes. In this prototype the browser can compile Web Native HTML/CSS/JS directly; arbitrary languages need the server-side Workers compiler pipeline to be connected.'}
$('#editor').addEventListener('input',()=>{$('#status').textContent='Modified';updateCursor()});$('#editor').addEventListener('keyup',updateCursor);$('#editor').addEventListener('click',updateCursor);
$('#buildBtn').onclick=build;$('#refreshBtn').onclick=nativePreview;$('#closePreview').onclick=()=>$('#previewDrawer').classList.remove('open');
$('#runtime').onchange=e=>{state.runtime=e.target.value;$('#targetLabel').textContent=state.runtime};$('#language').onchange=e=>{state.language=e.target.value};
$('#newFileBtn').onclick=()=>{const n=prompt('File path');if(!n)return;if(state.files[n])return alert('File already exists');state.files[n]='';openFile(n)};
$('#aiForm').onsubmit=e=>{e.preventDefault();const q=$('#aiInput').value.trim();if(!q)return;const box=$('#aiMessages');box.innerHTML+=`<div class="msg user">${escapeHtml(q)}</div><div class="msg ai">${escapeHtml(aiReply(q))}</div>`;$('#aiInput').value='';box.scrollTop=box.scrollHeight};
$('#aiBtn').onclick=()=>{$('.rightbar').style.display='flex'};$('#closeAi').onclick=()=>{$('.rightbar').style.display='none'};
$('#deployBtn').onclick=()=>{$('#projectId').value=state.projectId||randomId();$('#deployUrl').textContent='/pages/#'+$('#projectId').value;$('#deployModal').classList.remove('hidden')};
$('#cancelDeploy').onclick=()=>$('#deployModal').classList.add('hidden');
$('#confirmDeploy').onclick=()=>{state.projectId=$('#projectId').value.trim()||randomId();$('#deployUrl').textContent='/pages/#'+state.projectId;$('#projectTitle').textContent=state.projectId;$('#deployModal').classList.add('hidden');$('#status').textContent='Deployment queued: /pages/#'+state.projectId};
function randomId(){return crypto.randomUUID().replaceAll('-','').slice(0,12)}
renderTree();renderTabs();openFile('index.html');