import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const starter={"index.html":"<!doctype html>\n<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>GutHeb Space</title></head><body><main><h1>Hello GutHeb Workers</h1><p>Edit this project and deploy it.</p></main></body></html>","src/main.js":"document.body.dataset.runtime=\"web-native\";"};
const clean=s=>s.replace(/[^a-zA-Z0-9._-]/g,"-").replace(/-+/g,"-").slice(0,48)||"gutheb-space";

function PagesViewer(){
 const[id]=useState(()=>decodeURIComponent(location.hash.replace(/^#/,"")));
 const[status,setStatus]=useState("Cargando publicación…"),[url,setUrl]=useState("");
 useEffect(()=>{if(!id){setStatus("Falta el ID de publicación.");return}
 fetch("/api/deployment/"+encodeURIComponent(id)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"No se encontró la publicación.");setUrl(d.url);setStatus("")}).catch(e=>setStatus(e.message))
 },[id]);
 return <div className="viewer"><header className="viewerBar"><div className="brand"><img src="/gutheb-workers.svg?v=20260927"/><strong>GutHeb Pages</strong></div><a href="/">← Workers</a></header>{status?<div className="viewerState">{status}</div>:<iframe title="GutHeb Pages" src={url}/>}</div>
}

function App(){
 const[files,setFiles]=useState(()=>JSON.parse(localStorage.getItem("ghw-files")||"null")||starter),[active,setActive]=useState("index.html"),[runtime,setRuntime]=useState("Web Native"),[preview,setPreview]=useState(false),[project,setProject]=useState(()=>localStorage.getItem("ghw-project")||"untitled-space"),[ai,setAi]=useState(""),[log,setLog]=useState([]),[busy,setBusy]=useState(false),[deploy,setDeploy]=useState(null),[error,setError]=useState(""),[account,setAccount]=useState(null),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState("login"),[authForm,setAuthForm]=useState({username:"",email:"",password:""}),[accountError,setAccountError]=useState(""),[repoId,setRepoId]=useState(null),[view,setView]=useState("canvas"),[panel,setPanel]=useState("chat");
 useEffect(()=>localStorage.setItem("ghw-files",JSON.stringify(files)),[files]);useEffect(()=>localStorage.setItem("ghw-project",project),[project]);
 useEffect(()=>{fetch("/api/account",{credentials:"include"}).then(async r=>r.ok?r.json():null).then(d=>d&&setAccount(d.user)).catch(()=>{})},[]);
 const accountAction=async e=>{e.preventDefault();setAccountError("");try{const action=authMode==="register"?"register":"login";const r=await fetch("/api/account",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,username:authForm.username,email:authForm.email,password:authForm.password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo conectar la cuenta.");setAccount(d.user);setAuthOpen(false);setLog(x=>[...x,"Cuenta conectada: "+d.user.name])}catch(e){setAccountError(e.message)}};
 const savePages=async(currentFiles=files)=>{if(!account){setAuthOpen(true);return null}const r=await fetch("/api/pages",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"project",project:{id:repoId||undefined,name:project,slug:project,description:"GutHeb Workers website",files:currentFiles}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo guardar workers-pages.");setRepoId(d.id);return d};
 const sync=async()=>{try{setBusy(true);await savePages(files);setLog(x=>[...x,"✓ Guardado automáticamente en workers-pages"])}catch(e){setLog(x=>[...x,"✕ "+e.message])}finally{setBusy(false)}};
 const ask=async()=>{const q=ai.trim();if(!q)return;setAi("");setLog(x=>[...x,"Tú: "+q,"⟳ Construyendo…"]);try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q,history:log.slice(-8)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI request failed");setLog(x=>[...x,"GutHeb AI: "+String(d.output||"Listo.")])}catch(e){setLog(x=>[...x,"✕ AI: "+e.message])}};
 const update=v=>setFiles(x=>({...x,[active]:v}));
 const addFile=()=>{const p=prompt("Nombre del archivo","src/App.jsx");if(p&&!files[p]){setFiles(x=>({...x,[p]:""}));setActive(p)}};
 const addFolder=()=>{const p=prompt("Nombre de la carpeta","src/components");if(p){const f=p.replace(/\/$/,"")+"/.gitkeep";setFiles(x=>({...x,[f]:""}))}};
 const code=files[active]||"";
 return <div className="base44App">
  <header className="b44Top"><div className="b44Brand"><img src="/gutheb-workers.svg?v=20260927"/><span>GutHeb</span></div><div className="b44Project"><span>{project}</span><button onClick={()=>setProject(prompt("Nombre del proyecto",project)||project)}>⌄</button></div><div className="b44TopActions"><button onClick={()=>setView("canvas")} className={view==="canvas"?"sel":""}>Canvas</button><button onClick={()=>setView("code")} className={view==="code"?"sel":""}>Code</button><button onClick={()=>setPanel("chat")} className={panel==="chat"?"sel":""}>AI</button><button onClick={sync}>{busy?"Saving…":"Save"}</button><button className="publish" onClick={sync}>Publish</button><div className="avatar">{account?(account.name||"U")[0].toUpperCase():"?"}</div></div></header>
  <div className="b44Body">
   <aside className="b44Left"><button className={panel==="chat"?"leftSel":""} onClick={()=>setPanel("chat")}>✦<span>Chat</span></button><button className={panel==="pages"?"leftSel":""} onClick={()=>setPanel("pages")}>▤<span>Pages</span></button><button className={panel==="files"?"leftSel":""} onClick={()=>setPanel("files")}>⌁<span>Files</span></button><button className={panel==="theme"?"leftSel":""} onClick={()=>setPanel("theme")}>◐<span>Theme</span></button><button className={panel==="settings"?"leftSel":""} onClick={()=>setPanel("settings")}>⚙<span>Settings</span></button></aside>
   {panel==="chat"&&<aside className="b44Chat"><div className="chatHead"><b>Build with AI</b><span>New chat</span></div><div className="chatWelcome"><div className="spark">✦</div><h2>What do you want to build?</h2><p>Describe your idea and GutHeb will build the site with you.</p></div><div className="chatLog">{log.slice(-8).map((x,i)=><div key={i} className={x.startsWith("Tú:")?"userMsg":"aiMsg"}>{x}</div>)}</div><div className="chatBox"><textarea value={ai} onChange={e=>setAi(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Describe what you want to change…"/><button onClick={ask}>↑</button></div></aside>}
   {panel!=="chat"&&<aside className="b44Inspector"><b>{panel==="pages"?"Pages":panel==="files"?"Files":panel==="theme"?"Theme":"Settings"}</b>{panel==="files"&&<><button onClick={addFile}>＋ New file</button><button onClick={addFolder}>＋ New folder</button>{Object.keys(files).map(f=><button key={f} onClick={()=>setActive(f)}>{f}</button>)}</>}{panel==="theme"&&<><label>Runtime<select value={runtime}onChange={e=>setRuntime(e.target.value)}>{["Web Native","Vite","React","Vue","Svelte","Astro","Next.js","Node","Python","Rust","Go","Java","C#","C++","PHP"].map(x=><option key={x}>{x}</option>)}</select></label><p>Responsive design · Live preview</p></>}{panel==="pages"&&<p>Every page is stored in workers-pages with its files, build assets and deployment metadata.</p>}</aside>}
   <main className="b44Canvas">{view==="canvas"?<><div className="canvasToolbar"><span>Desktop</span><span>100%</span><button onClick={()=>setPreview(true)}>Preview ↗</button></div><div className="infiniteCanvas"><div className="siteFrame"><div className="siteFrameBar"><span>●</span><span>●</span><span>●</span><em>{project}</em></div><iframe title="canvas" sandbox="allow-scripts" srcDoc={files["index.html"]||"<main><h1>Start building</h1></main>"}/></div></div></>:<div className="codeView"><div className="codeTabs">{Object.keys(files).map(f=><button className={f===active?"active":""} key={f} onClick={()=>setActive(f)}>{f}</button>)}</div><textarea spellCheck="false"value={code}onChange={e=>update(e.target.value)}/></div>}</main>
  </div>
  {preview&&<div className="fullPreview"><button onClick={()=>setPreview(false)}>×</button><iframe title="preview" sandbox="allow-scripts" srcDoc={files["index.html"]||"<h1>No index.html</h1>"}/></div>}
  {authOpen&&<div className="modal"><div className="deployCard"><b>{authMode==="register"?"CREATE ACCOUNT":"SIGN IN"}</b><form onSubmit={accountAction}><input placeholder="Username" value={authForm.username}onChange={e=>setAuthForm({...authForm,username:e.target.value})}/><input type="email" required placeholder="Email" value={authForm.email}onChange={e=>setAuthForm({...authForm,email:e.target.value})}/><input type="password" required placeholder="Password" value={authForm.password}onChange={e=>setAuthForm({...authForm,password:e.target.value})}/>{accountError&&<div className="error">{accountError}</div>}<button className="publish">Continue</button></form></div></div>}
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);