import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const starter={"index.html":"<!doctype html>\n<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>GutHeb Space</title></head><body><main><h1>Hello GutHeb Workers</h1><p>Edit this project and deploy it.</p></main></body></html>","src/main.js":"document.body.dataset.runtime=\"web-native\";"};
const clean=s=>s.replace(/[^a-zA-Z0-9._-]/g,"-").replace(/-+/g,"-").slice(0,48)||"gutheb-space";

function PagesViewer(){
 const[id]=useState(()=>decodeURIComponent(location.hash.replace(/^#/,"")));
 const[status,setStatus]=useState("Cargando publicación…"),[html,setHtml]=useState("");
 useEffect(()=>{if(!id){setStatus("Falta el ID de publicación.");return}
 fetch("/api/deployment/"+encodeURIComponent(id)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"No se encontró la publicación.");const index=(d.files||[]).find(x=>x.path==="index.html");setHtml(index?.content||"<main><h1>GutHeb Pages</h1></main>");setStatus("")}).catch(e=>setStatus(e.message))
 },[id]);
 return <div className="viewer"><header className="viewerBar"><div className="brand"><img src="/gutheb-workers.svg?v=20260927"/><strong>GutHeb Pages</strong></div><a href="/">← Workers</a></header>{status?<div className="viewerState">{status}</div>:<iframe title="GutHeb Pages" sandbox="allow-scripts" srcDoc={html}/>}</div>
}

function App(){
 const[mode,setMode]=useState(()=>location.pathname==="/builder"?"builder":location.pathname==="/signup"?"register":location.pathname==="/reset-password"?"reset":"login"),[theme,setTheme]=useState(()=>localStorage.getItem("ghw-theme")||"dark");
 const[files,setFiles]=useState(()=>JSON.parse(localStorage.getItem("ghw-files")||"null")||starter),[active,setActive]=useState("index.html"),[project,setProject]=useState(()=>localStorage.getItem("ghw-project")||"untitled-space"),[ai,setAi]=useState(""),[log,setLog]=useState([]),[panel,setPanel]=useState("chat"),[view,setView]=useState("canvas"),[account,setAccount]=useState(null),[authMode,setAuthMode]=useState(()=>location.pathname==="/signup"?"register":location.pathname==="/reset-password"?"reset":"login"),[authForm,setAuthForm]=useState({username:"",email:"",password:""}),[accountError,setAccountError]=useState(""),[busy,setBusy]=useState(false),[repoId,setRepoId]=useState(null);
 useEffect(()=>localStorage.setItem("ghw-files",JSON.stringify(files)),[files]);useEffect(()=>localStorage.setItem("ghw-project",project),[project]);useEffect(()=>localStorage.setItem("ghw-theme",theme),[theme]);
 useEffect(()=>{fetch("/api/account",{credentials:"include"}).then(async r=>r.ok?r.json():null).then(d=>{if(d&&d.user){setAccount(d.user);setMode(location.pathname==="/builder"?"builder":"home")}}).catch(()=>{})},[]);
 const go=m=>{setAuthMode(m);setAccountError("");const path=m==="register"?"/signup":m==="reset"?"/reset-password":"/login";history.replaceState(null,"",path);setMode(m)};
 const accountAction=async e=>{e.preventDefault();setAccountError("");if(authMode==="reset"){setAccountError("El restablecimiento por correo aún necesita configurar el servicio de correo.");return}try{const action=authMode==="register"?"register":"login";const r=await fetch("/api/account",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,username:authForm.username,email:authForm.email,password:authForm.password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo conectar la cuenta.");setAccount(d.user);setMode("home");history.replaceState(null,"","/");}catch(e){setAccountError(e.message)}};
 const savePages=async()=>{if(!account){go("login");return}setBusy(true);try{const r=await fetch("/api/pages",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"project",project:{id:repoId||undefined,name:project,slug:project,description:"GutHeb Workers project",files}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo guardar.");setRepoId(d.id);setLog(x=>[...x,"✓ Guardado en workers-pages"])}catch(e){setLog(x=>[...x,"✕ "+e.message])}finally{setBusy(false)}};
 const runTests=async(sourceFiles=files)=>{const out=[];for(const[path,content]of Object.entries(sourceFiles)){if(path.endsWith(".html")){try{const d=new DOMParser().parseFromString(content,"text/html");out.push("✓ HTML "+path+(d.querySelector("parsererror")?" tiene errores":" OK"))}catch(e){out.push("✕ HTML "+path+": "+e.message)}}else if(path.endsWith(".css")){try{const sheet=new CSSStyleSheet();sheet.replaceSync(content);out.push("✓ CSS "+path+" OK")}catch(e){out.push("✕ CSS "+path+": "+e.message)}}else if(path.endsWith(".js")||path.endsWith(".jsx")){try{const stripped=content.replace(/^\\s*import[^;]+;?/gm,"").replace(/^\\s*export\\s+(default\\s+)?/gm,"");new Function(stripped);out.push("✓ JS "+path+" syntax OK")}catch(e){out.push("✕ JS "+path+": "+e.message)}}}setLog(x=>[...x,"🧪 Tests de la aplicación:",...out]);return out};
const ask=async()=>{const q=ai.trim();if(!q)return;setAi("");setLog(x=>[...x,"Tú: "+q,"⟳ GutHeb AI está trabajando en los archivos…"]);try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q,history:log.slice(-8),files})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI request failed");let changed=false;let nextFiles={...files};const ops=[...(d.operations||[]),...(d.backend_actions||[]).map(x=>({type:"write_file",path:x.path,content:x.content}))];for(const op of ops){const path=String(op.path||"").replace(/^\/+|^\.\.\//g,"");if(!path||path.includes(".."))continue;if(op.type==="write_file"||op.type==="write_backend"){nextFiles[path]=String(op.content||"");setActive(path);changed=true;setLog(x=>[...x,"✓ AI escribió "+path])}else if(op.type==="delete_file"){delete nextFiles[path];changed=true;setLog(x=>[...x,"✓ AI eliminó "+path])}else if(op.type==="create_folder"){const p=path.replace(/\/$/,"")+"/.gitkeep";nextFiles[p]="";changed=true;setLog(x=>[...x,"✓ AI creó "+path])}}if(changed){setFiles(nextFiles);setBusy(true);try{const sr=await fetch("/api/pages",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"project",project:{id:repoId||undefined,name:project,slug:project,description:"GutHeb Workers project",files:nextFiles}})});const sd=await sr.json();if(!sr.ok)throw new Error(sd.error||"No se pudo persistir el cambio.");setRepoId(sd.id);setLog(x=>[...x,"✓ Cambios de IA guardados en workers-pages"])}finally{setBusy(false)}}if((d.search_queries||[]).length){for(const query of d.search_queries.slice(0,3)){const sr=await fetch("/api/search?q="+encodeURIComponent(query));const sd=await sr.json();setLog(x=>[...x,"🔎 Búsqueda: "+query,...(sd.results||[]).slice(0,5).map(z=>"• "+z.title+(z.url?" · "+z.url:""))])}}if((d.tests||[]).length||changed)await runTests(nextFiles);setLog(x=>[...x,"GutHeb AI: "+String(d.message||"Listo.")])}catch(e){setLog(x=>[...x,"✕ AI: "+e.message])}};
 const update=v=>setFiles(x=>({...x,[active]:v}));
 const addFile=()=>{const p=prompt("Nombre del archivo","src/App.jsx");if(p&&!files[p]){setFiles(x=>({...x,[p]:""}));setActive(p)}};
 const addFolder=()=>{const p=prompt("Nombre de la carpeta","src/components");if(p)setFiles(x=>({...x,[p.replace(/\/$/,"")+"/.gitkeep"]:""}))};
 const startProject=()=>{if(!account){go("login");return}setMode("builder");history.replaceState(null,"","/builder")};
 if(location.pathname.startsWith("/pages/"))return <PagesViewer/>; if(mode==="login"||mode==="register"||mode==="reset")return <AuthModal mode={authMode} setMode={go} form={authForm} setForm={setAuthForm} error={accountError} onSubmit={accountAction}/>;
 if(mode==="home")return <Home account={account} project={project} setProject={setProject} onStart={startProject} onLogin={()=>go("login")} onRegister={()=>go("register")}/>;
 return <Builder theme={theme} setTheme={setTheme} repoId={repoId} account={account} project={project} setProject={setProject} files={files} setFiles={setFiles} active={active} setActive={setActive} ai={ai} setAi={setAi} log={log} setLog={setLog} panel={panel} setPanel={setPanel} view={view} setView={setView} update={update} addFile={addFile} addFolder={addFolder} savePages={savePages} busy={busy} ask={ask} runTests={runTests}/>;
}


function AiQuestionCard({question,options,onChoose}){return <div className="aiQuestionCard"><div className="aiQuestionIcon">✦</div><div className="aiQuestionBody"><div className="aiQuestionLabel">GUTHEB AI</div><h3>{question}</h3><div className="aiQuestionOptions">{options.map((x,i)=><button key={i} onClick={()=>onChoose(x)}>{x}<span>↗</span></button>)}</div></div></div>}
function AuthModal({mode,setMode,form,setForm,error,onSubmit}){const reset=mode==="reset";const register=mode==="register";return <div className="authPage"><div className="authGlow"/><main className="authShell"><div className="authBrand"><img src="/gutheb-workers.svg?v=20260927"/><span>GutHeb Workers</span></div><section className="authCard"><div className="eyebrow">GUTHEB WORKERS</div><h1>{reset?"Reset your password":register?"Create your account":"Welcome back"}</h1><p>{reset?"Enter your email and we’ll send instructions to reset your password.":register?"Create an account before you start building.":"Sign in before creating or editing an application."}</p><form onSubmit={onSubmit}>{register&&<input required placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>{!reset&&<input required minLength={8} type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>} {error&&<div className="error">{error}</div>}<button className="authPrimary" type="submit">{reset?"Send reset instructions":register?"Create account":"Log in"}</button></form>{!reset&&<button className="authLink" onClick={()=>setMode("reset")}>Forgot password?</button>}<div className="authBottom">{reset?"Remembered your password?":"Don’t have an account?"} <button onClick={()=>setMode(reset?"login":register?"login":"register")}>{reset?"Log in":register?"Log in":"Sign up"}</button></div></section><small className="authFoot">You must be signed in to create a GutHeb Workers project.</small></main></div>}

function Welcome({onStart,onLogin}){return <div className="welcomePage"><div className="ambientGlow glowA"/><div className="ambientGlow glowB"/><header className="welcomeNav"><div className="b44Brand"><img src="/gutheb-workers.svg?v=20260927"/><span>GutHeb</span></div><nav><a href="#product">Product</a><a href="#solutions">Solutions</a><a href="#resources">Resources</a><a href="#pricing">Pricing</a></nav><div><button className="plainBtn" onClick={onLogin}>Log in</button><button className="darkBtn" onClick={onStart}>Start building</button></div></header><main className="welcomeHero"><div className="eyebrow">GUTHEB WORKERS</div><h1>Build your app.<br/><i>Just describe it.</i></h1><p>Turn an idea into a real, working product with AI. Start free, explore the result, and keep refining it in conversation.</p><div className="welcomePrompt"><div>✦</div><textarea placeholder="Describe the app you want to build…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();onStart()}}}/><button onClick={onStart}>Create app ↗</button></div><div className="heroMeta"><span>No setup</span><span>•</span><span>Live preview</span><span>•</span><span>AI iteration</span></div></main><section className="welcomeSection" id="product"><div className="sectionIntro"><span className="eyebrow">ONE WORKSPACE</span><h2>From idea to something real.</h2><p>Build screens, flows and functionality together, then keep refining everything with natural language.</p></div><div className="featureGrid"><article><b>✦</b><h3>Build with AI</h3><p>Describe what you need and keep the conversation going as your project evolves.</p></article><article><b>◫</b><h3>See every page</h3><p>Work visually with live page previews instead of staring at an empty code editor.</p></article><article><b>◌</b><h3>Control the design</h3><p>Keep global visual choices consistent across your project.</p></article><article><b>⌁</b><h3>Open the code</h3><p>When you want deeper control, switch from visual building to your files.</p></article></div></section><section className="welcomeSection alt" id="solutions"><div className="sectionIntro"><span className="eyebrow">START ANYWHERE</span><h2>Apps, websites, tools and experiments.</h2><p>GutHeb Workers is designed around the same prompt → build → refine loop.</p></div></section><footer className="welcomeFooter"><div className="b44Brand"><img src="/gutheb-workers.svg?v=20260927"/><span>GutHeb</span></div><span>Build something real.</span></footer></div>}


function Home({account,project,onStart,onLogin,onRegister}){return <div className="homePage"><header className="homeNav"><div className="b44Brand"><img src="/gutheb-workers.svg?v=20260927"/><span>GutHeb</span></div><div>{account?<span>{account.name||account.username}</span>:<><button onClick={onLogin}>Log in</button><button onClick={onRegister}>Sign up</button></>}</div></header><main className="homeMain"><div className="homeTitle"><span className="eyebrow">WORKSPACE</span><h1>What are you building?</h1><p>Start a project, then shape it with GutHeb AI.</p></div><div className="appGrid"><button className="newAppCard" onClick={onStart}><strong>＋</strong><span>New app</span><small>Start from an idea</small></button><button className="appCard" onClick={onStart}><div className="fakeThumb">✦</div><strong>{project}</strong><small>GutHeb Workers project</small></button></div></main></div>}

function Builder({theme,setTheme,repoId,account,project,setProject,files,setFiles,active,setActive,ai,setAi,log,setLog,panel,setPanel,view,setView,update,addFile,addFolder,savePages,busy,ask,runTests}){
 const [device,setDevice]=useState("desktop");
 const [zoom,setZoom]=useState(100);
 const [showInspector,setShowInspector]=useState(true);
 const fileNames=Object.keys(files);
 const publish=async()=>{await savePages();if(!repoId){setLog(x=>[...x,"✕ Guarda el proyecto y vuelve a publicar para obtener el ID."]);return}try{const r=await fetch("/api/pages",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"deployment",projectId:repoId,status:"published",metadata:{runtime:"web-native",device}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo publicar.");setLog(x=>[...x,"✓ Publicado en /pages/#"+d.id]);history.replaceState(null,"","/pages/#"+d.id)}catch(e){setLog(x=>[...x,"✕ Publish: "+e.message])}};
 return <div className={"studio "+theme}>
  <header className="studioTop">
   <div className="studioBrand"><img src="/gutheb-workers.svg?v=20260927"/><span>GutHeb</span><i>/</i><button onClick={()=>setProject(prompt("Project name",project)||project)}>{project}</button></div>
   <div className="studioMode"><button className={view==="canvas"?"active":""} onClick={()=>setView("canvas")}>Build</button><button className={view==="code"?"active":""} onClick={()=>setView("code")}>Code</button></div>
   <div className="studioActions"><span className="saveState">{busy?"Saving…":"Saved"}</span><button onClick={()=>setTheme(theme==="dark"?"light":"dark")} title="Toggle theme">{theme==="dark"?"☼":"☾"}</button><button onClick={()=>setShowInspector(!showInspector)}>Inspector</button><button className="aiTop" onClick={()=>setPanel("chat")}>✦ AI</button><button className="publishBtn" onClick={publish}>Publish ↗</button><div className="avatar">{(account?.username||account?.name||"U")[0].toUpperCase()}</div></div>
  </header>
  <div className="studioBody">
   <aside className="studioRail">
    <button className={panel==="chat"?"on":""} onClick={()=>setPanel("chat")}>✦<small>AI</small></button>
    <button className={panel==="files"?"on":""} onClick={()=>setPanel("files")}>▤<small>Files</small></button>
    <button className={panel==="pages"?"on":""} onClick={()=>setPanel("pages")}>▦<small>Pages</small></button>
    <button className={panel==="theme"?"on":""} onClick={()=>setPanel("theme")}>◐<small>Design</small></button>
    <div className="railSpacer"/>
    <button onClick={runTests}>✓<small>Test</small></button>
    <button onClick={()=>setPanel("settings")}>⚙<small>Settings</small></button>
   </aside>
   <aside className="studioPanel">
    {panel==="chat"&&<><div className="panelTitle"><b>AI Builder</b><button onClick={()=>setLog([])}>＋ New</button></div><div className="aiIntro"><div className="aiOrb">✦</div><h2>Build anything.</h2><p>Ask me to edit the app, create files, build backend functions, search the web or test the project.</p><div className="quickPrompts"><button onClick={()=>setAi("Redesign this interface with a polished dark glass aesthetic.")}>Redesign UI <span>↗</span></button><button onClick={()=>setAi("Inspect the current app, fix errors and test it.")}>Fix & test <span>↗</span></button><button onClick={()=>setAi("Create the backend API needed for this app.")}>Build backend <span>↗</span></button></div></div><div className="aiLog">{log.slice(-12).map((x,i)=><div key={i} className={x.startsWith("Tú:")?"msg user":"msg"}>{x}</div>)}</div><div className="aiComposer"><textarea value={ai} onChange={e=>setAi(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Describe a change…"/><div><span>Enter to send · Shift+Enter newline</span><button onClick={ask}>↑</button></div></div></>}
    {panel==="files"&&<><div className="panelTitle"><b>Project files</b><div><button onClick={addFile}>＋</button><button onClick={addFolder}>□</button></div></div><div className="fileTree">{fileNames.map(f=><button className={f===active?"file active":"file"} key={f} onClick={()=>{setActive(f);setView("code")}}><span>{f.endsWith(".html")?"◇":f.endsWith(".css")?"#":f.endsWith(".js")||f.endsWith(".jsx")?"JS":"•"}</span>{f}</button>)}</div></>}
    {panel==="pages"&&<><div className="panelTitle"><b>Pages</b></div><div className="panelContent"><div className="miniCard"><b>Home</b><span>/</span><small>index.html</small></div><button className="outlineBtn" onClick={()=>setAi("Create a new page and wire it into the app.")}>＋ Add page with AI</button></div></>}
    {panel==="theme"&&<><div className="panelTitle"><b>Design system</b></div><div className="panelContent"><p>Use AI to change typography, spacing, colors and responsive behavior across the project.</p><button className="outlineBtn" onClick={()=>{setAi("Redesign the whole application interface. Keep it responsive and polished.");setPanel("chat")}}>✦ Redesign with AI</button><button className="outlineBtn" onClick={runTests}>✓ Run tests</button></div></>}
    {panel==="settings"&&<><div className="panelTitle"><b>Project settings</b></div><div className="panelContent"><label>Project name<input value={project} onChange={e=>setProject(clean(e.target.value))}/></label><button className="outlineBtn" onClick={savePages}>Save project</button></div></>}
   </aside>
   <main className="studioMain">
    <div className="studioToolbar"><div className="deviceTools"><button className={device==="desktop"?"active":""} onClick={()=>setDevice("desktop")}>Desktop</button><button className={device==="tablet"?"active":""} onClick={()=>setDevice("tablet")}>Tablet</button><button className={device==="phone"?"active":""} onClick={()=>setDevice("phone")}>Phone</button></div><div className="canvasTools"><button onClick={()=>setZoom(Math.max(50,zoom-10))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(Math.min(150,zoom+10))}>＋</button><button onClick={()=>setZoom(100)}>Fit</button><button onClick={()=>setShowInspector(!showInspector)}>◧</button></div></div>
    {view==="canvas"?<div className="workspaceCanvas"><div className={"previewShell "+device} style={{transform:"scale("+zoom/100+")"}}><div className="previewChrome"><span/><span/><span/><em>{project}.gutheb</em></div><iframe title="live preview" sandbox="allow-scripts allow-forms" srcDoc={files["index.html"]||"<main><h1>Start building</h1></main>"}/></div></div>:<div className="editor"><div className="editorTabs">{fileNames.map(f=><button className={f===active?"active":""} key={f} onClick={()=>setActive(f)}>{f}<span>×</span></button>)}</div><div className="editorBody"><div className="lineNums">{String(files[active]||"").split("\n").map((_,i)=><span key={i}>{i+1}</span>)}</div><textarea spellCheck="false" value={files[active]||""} onChange={e=>update(e.target.value)}/></div></div>}
    <div className="studioStatus"><span>● {busy?"Syncing":"Ready"}</span><span>{fileNames.length} files</span><span>Web runtime</span><span>GutHeb Workers</span></div>
   </main>
   {showInspector&&<aside className="rightInspector"><div className="panelTitle"><b>Inspector</b></div><div className="inspectBlock"><span>Selection</span><strong>{view==="code"?active:"Home page"}</strong><small>{device} · {zoom}%</small></div><div className="inspectBlock"><span>Runtime</span><strong>Web native</strong><small>HTML · CSS · JS</small></div><div className="inspectBlock"><span>Deployment</span><strong>/pages/</strong><small>Cloudflare Pages</small></div><button className="outlineBtn" onClick={runTests}>Run application tests</button></aside>}
  </div>
 </div>
}

createRoot(document.getElementById("root")).render(<App/>);