import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const starter={"index.html":"<!doctype html>\n<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>GutHeb Space</title></head><body><main><h1>Hello GutHeb Workers</h1><p>Edit this project and deploy it.</p></main></body></html>","src/main.js":"document.body.dataset.runtime=\"web-native\";"};
const clean=s=>s.replace(/[^a-zA-Z0-9._-]/g,"-").replace(/-+/g,"-").slice(0,48)||"gutheb-space";

function PagesViewer(){
 const[id]=useState(()=>decodeURIComponent(location.hash.replace(/^#/,"")));
 const[status,setStatus]=useState("Cargando publicación…"),[url,setUrl]=useState("");
 useEffect(()=>{if(!id){setStatus("Falta el ID de publicación.");return}
 fetch("/api/deployment/"+encodeURIComponent(id)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"No se encontró la publicación.");setUrl(d.url);setStatus("")}).catch(e=>setStatus(e.message))
 },[id]);
 return <div className="viewer"><header className="viewerBar"><div className="brand"><img src="/gutheb-workers.svg?v=20260927"/><strong>GutHeb Pages</strong></div><a href="/">← Workers</a></header>{status?<div className="viewerState">{status}</div>:<iframe title="GutHeb Pages" src={url}/>}</div>
}

function App(){
 const[files,setFiles]=useState(()=>JSON.parse(localStorage.getItem("ghw-files")||"null")||starter),[active,setActive]=useState("index.html"),[runtime,setRuntime]=useState("Web Native"),[preview,setPreview]=useState(false),[project,setProject]=useState(()=>localStorage.getItem("ghw-project")||"untitled-space"),[ai,setAi]=useState(""),[log,setLog]=useState([]),[busy,setBusy]=useState(false),[deploy,setDeploy]=useState(null),[error,setError]=useState("");
 const[account,setAccount]=useState(null),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState("login"),[authForm,setAuthForm]=useState({username:"",email:"",password:""}),[accountError,setAccountError]=useState(""),[repoId,setRepoId]=useState(null);
 useEffect(()=>localStorage.setItem("ghw-files",JSON.stringify(files)),[files]);useEffect(()=>localStorage.setItem("ghw-project",project),[project]);
 useEffect(()=>{fetch("/api/account",{credentials:"include"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setAccount(d.user)).catch(()=>{})},[]);
 const accountAction=async e=>{e.preventDefault();setAccountError("");try{const action=authMode==="register"?"register":"login";const r=await fetch("/api/account",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,username:authForm.username,email:authForm.email,password:authForm.password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo conectar la cuenta.");setAccount(d.user);setAuthOpen(false);setAuthForm({username:"",email:"",password:""});setLog(x=>[...x,"✓ Cuenta GutHeb conectada: "+d.user.name])}catch(e){setAccountError(e.message)}};
 const syncProject=async()=>{if(!account){setAuthOpen(true);return}setBusy(true);try{const repo={id:repoId||undefined,name:clean(project),owner:account.name,visibility:"Public",language:runtime,description:"GutHeb Workers workspace",license:"MIT",stars:0,forks:0,files,folders:Object.keys(files).filter(x=>x.endsWith("/.gitkeep")).map(x=>x.slice(0,-8))};const r=await fetch("/api/account",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"repo",repo})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo sincronizar el proyecto.");setRepoId(d.id);setLog(x=>[...x,"✓ "+project+" sincronizado con GutHeb","✓ Repositorio: "+d.id])}catch(e){setLog(x=>[...x,"✕ Sync: "+e.message])}finally{setBusy(false)}};
 const code=files[active]??"",count=Object.keys(files).length;
 const update=v=>setFiles(x=>({...x,[active]:v}));
 const addFile=()=>{const p=prompt("Ruta del archivo","src/App.jsx");if(!p||files[p]!=null)return;setFiles(x=>({...x,[p]:""}));setActive(p)};
 const addFolder=()=>{const p=prompt("Ruta de carpeta","src/components");if(!p)return;const f=p.replace(/\/$/,"")+"/.gitkeep";setFiles(x=>({...x,[f]:""}));setActive(f)};
 const previewBuild=()=>{setPreview(true);setLog(x=>[...x,"✓ Workspace compilable","✓ "+count+" archivos resueltos","✓ Vista previa generada"])};
 const deployNow=async()=>{if(busy)return;setBusy(true);setError("");setLog(x=>[...x,"⟳ Compilando para Cloudflare Pages…"]);try{const r=await fetch("/api/deploy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project:clean(project),runtime,files})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falló el deployment.");setDeploy(d);setLog(x=>[...x,"✓ Deployment "+d.id+" creado","✓ "+d.url])}catch(e){setError(e.message);setLog(x=>[...x,"✕ "+e.message])}finally{setBusy(false)}};
 const ask=async()=>{const q=ai.trim();if(!q)return;setLog(x=>[...x,"AI → "+q,"⟳ GutHeb AI está procesando…"]);setAi("");try{const res=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q,history:[]})});const d=await res.json();if(!res.ok)throw new Error(d.error||"AI request failed");setLog(x=>[...x,"AI ← "+String(d.output||"No response.")])}catch(e){setLog(x=>[...x,"✕ AI: "+e.message])}};
 if(location.pathname==="/pages/")return <PagesViewer/>;
 return <div className="app">
  <header className="top"><div className="brand"><img src="/gutheb-workers.svg"/><strong>GutHeb Workers</strong><span>SPACE</span></div><div className="projectWrap"><small>PROJECT</small><input value={project}onChange={e=>setProject(e.target.value)}/></div><div className="actions"><button onClick={syncProject}>{account?`↥ Sync ${account.name}`:"Sign in"}</button><button onClick={previewBuild}>Preview</button><button className="primary"onClick={deployNow}disabled={busy}>{busy?"Compiling & deploying…":"Compile & Deploy"}</button></div></header>
  <div className="subbar"><span>WORKSPACE / {project}</span><span>● {busy?"BUILDING":"READY"}</span><span>{runtime} · {count} files</span></div>
  <main className="layout">
   <aside className="panel explorer"><div className="panelTitle">EXPLORER <button className="iconBtn"onClick={addFile}>+</button></div>{Object.keys(files).map(f=><button className={active===f?"file active":"file"}onClick={()=>setActive(f)}key={f}>◇ {f}</button>)}<button className="secondary full"onClick={addFolder}>＋ New folder</button><div className="panelTitle">RUNTIME</div><select value={runtime}onChange={e=>setRuntime(e.target.value)}>{["Web Native","Vite","React","Vue","Svelte","Astro","Next.js","Node","Python","Rust","Go","Java","C#","C++","PHP"].map(x=><option key={x}>{x}</option>)}</select></aside>
   <section className="editor"><div className="editorTop"><div className="tab">● {active}</div><button onClick={previewBuild}>Run</button></div><textarea spellCheck="false"value={code}onChange={e=>update(e.target.value)}/><footer><span>UTF-8</span><span>{runtime}</span><span>{code.length.toLocaleString()} chars</span><span>GutHeb native workspace</span></footer></section>
   <aside className="panel right"><div className="panelTitle">✦ AI BUILDER <span className="live">LIVE</span></div><p>Describe a workspace change.</p><textarea value={ai}onChange={e=>setAi(e.target.value)}placeholder="Build a React dashboard…"/><button className="secondary full"onClick={ask}>Send to AI</button><div className="panelTitle">BUILD LOG</div><div className="log">{log.length?log.slice(-12).map((x,i)=><div key={i}>{x}</div>):"Nothing built yet."}</div>{error&&<div className="error">{error}</div>}</aside>
  </main>
  {preview&&<section className="preview"><header><b>LIVE PREVIEW</b><button className="iconBtn"onClick={()=>setPreview(false)}>×</button></header><iframe title="preview"sandbox="allow-scripts"srcDoc={files["index.html"]||"<h1>No index.html</h1>"}/></section>}
  {authOpen&&<div className="modal"><div className="deployCard"><b>{authMode==="register"?"CREATE GUTHEB ACCOUNT":"SIGN IN TO GUTHEB"}</b><form onSubmit={accountAction}><input placeholder="Username" value={authForm.username} onChange={e=>setAuthForm({...authForm,username:e.target.value})}/><input type="email" required placeholder="Email" value={authForm.email} onChange={e=>setAuthForm({...authForm,email:e.target.value})}/><input type="password" required placeholder="Password" value={authForm.password} onChange={e=>setAuthForm({...authForm,password:e.target.value})}/>{accountError&&<div className="error">{accountError}</div>}<button className="primary full">Continue</button></form><button className="secondary full" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Create account":"I already have an account"}</button><button className="secondary full" onClick={()=>setAuthOpen(false)}>Cancel</button></div></div>}\n  {deploy&&<div className="modal"><div className="deployCard"><b className="success">✓ DEPLOYED</b><h2>{project}</h2><p>Deployment listo.</p><code>/pages/#{deploy.id}</code><a href={"/pages/#"+encodeURIComponent(deploy.id)}>Visualizar en GutHeb Pages ↗</a><a href={deploy.url}target="_blank"rel="noreferrer">Abrir Pages ↗</a><button className="secondary full"onClick={()=>setDeploy(null)}>Cerrar</button></div></div>}
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);